version: '2'

services:
  master:
    image: ppss1806/seaweedfs
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
  volume:
    image: ppss1806/seaweedfs
    ports:
      - 8080:8080
      - 18080:18080
    command: 'volume -mserver="master:9333" -port=8080 -max=100'
    depends_on:
      - master
  filer:
    image: ppss1806/seaweedfs
    ports:
      - 8888:8888
      - 18888:18888
    command: 'filer -master="master:9333"'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
  cronjob:
    image: ppss1806/seaweedfs # use a remote image
    command: 'cronjob'
    environment:
      # Run re-replication every 2 minutes
      CRON_SCHEDULE: '*/2 * * * * *' # Default: '*/5 * * * * *'
      WEED_MASTER: master:9333 # Default: localhost:9333
    depends_on:
      - master
      - volume
