version: '2'

services:
  master0:
    image: chrislusf/seaweedfs:local
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master0 -port=9333 -peers=master0:9333,master1:9334,master2:9335"
  master1:
    image: chrislusf/seaweedfs:local
    ports:
      - 9334:9334
      - 19334:19334
    command: "master -ip=master1 -port=9334 -peers=master0:9333,master1:9334,master2:9335"
  master2:
    image: chrislusf/seaweedfs:local
    ports:
      - 9335:9335
      - 19335:19335
    command: "master -ip=master2 -port=9335 -peers=master0:9333,master1:9334,master2:9335"
  volume:
    image: chrislusf/seaweedfs:local
    ports:
      - 8080:8080
      - 18080:18080
    command: 'volume -mserver="master0:9333,master1:9334,master2:9335" -port=8080 -ip=volume'
    depends_on:
      - master0
      - master1
      - master2
  filer:
    image: chrislusf/seaweedfs:local
    ports:
      - 8888:8888
      - 18888:18888
    command: 'filer -master="master0:9333,master1:9334,master2:9335"'
    depends_on:
      - master0
      - master1
      - master2
      - volume
  s3:
    image: chrislusf/seaweedfs:local
    ports:
      - 8333:8333
    command: 's3 -filer="filer:8888"'
    depends_on:
      - master0
      - master1
      - master2
      - volume
      - filer
